server:
  port: 80
#  servlet:
#    context-path: /api
spring:
  application:
    name: snapshot-api
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.130:8848

#security:
#  oauth2:
#    resource:
#      jwt:
#        key-uri: http://localhost:9999/oauth/token_key
#    client:
#      client-id: snapshot
#      client-secret: snapshot-secret
