server:
  port: 9527
spring:
  application:
    name: snapshot-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true               #开启从注册中心动态创建路由功能，利用微服务名进行路由
      routes:
        - id: snapshot-api-route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://snapshot-api      #匹配后提供服务的路由地址
          predicates:
            - Path=/test/**             # 断言，路径相匹配的进行路由
    nacos:
      discovery:
        server-addr: 192.168.10.130:8848



