server:
  port: 666
knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://192.168.174.128:8848/nacos
    routeAuth:
      enable: true
      username: nacos
      password: nacos
    routes:
      - name: 用户体系
        serviceName: service-user
        location: /aub/v2/api-docs?group=default
        servicePath: /
#      - name: Api接口
#        serviceName: snapshot-api
#        location: /v2/api-docs?group=default
#        servicePath: /
#      - name: 授权接口
#        serviceName: snapshot-oauth2-server
#        location: /v2/api-docs?group=default
#        servicePath: /
