version: '3.8'
services:
  minio:
    image: minio/minio:RELEASE.2023-06-02T23-17-26Z
    container_name: minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ./data:/data
      - ./conf:/root/.minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=gty20021112
    command: server /data --console-address ":9090"
