server:
  port: 9999
spring:
  application:
    name: snapshot-oauth2-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.174.128:3306/snapshot_auth?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.128:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.gty.oauth2.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
tencent:
  sms:
    secret-id: AKIDBBuMYT7WeV9XdS5SYMt98sLWQ3PUIvHM
    secret-key: pMcbIirjMinb7MK1RaT6SWJq64lBLEOH
    sdk-app-id: 1400824525
    sign-name: Snapshot随手拍
    template-id: 1824758

#keytool -genkey -alias snapshot -keypass snapshot -keyalg RSA -keysize 1024 -validity 365 -keystore C:\Users\User\Desktop\snapshot.keystore -storepass snapshot
